Lots of fixes

diff --git a/isobuilder b/isobuilder
--- a/isobuilder
+++ b/isobuilder
@@ -1,28 +1,18 @@
 #!/bin/bash
-
 SRC="$(pwd)/src"
 FIRSTBOOT_SRC="${SRC}/firstboot"
-ISO_SRC="$(pwd)/iso"
-
 
 # Logic Checks
 if [ ! -x /usr/bin/xorriso ]; then
-	echo "xorriso is not installed"
-	exit 1
+    echo "xorriso is not installed"
+    exit 1
 fi
-
+if [ ! -x /usr/bin/patch ]; then
+    echo "patch is not installed"
+    exit 1
+fi
 if [ ! -x /usr/bin/mcopy ]; then
 	echo "mcopy/mtools is not installed"
-	exit 1
-fi
-
-if [ ! -f /usr/lib/ISOLINUX/isohdpfx.bin ]; then
-	echo "isolinux is not installed"
-	exit 1
-fi
-
-if [ ! -x /usr/bin/patch ]; then
-	echo "patch is not installed"
 	exit 1
 fi
 
@@ -30,117 +20,121 @@ fi
 OPTIND=1
 while getopts d:p:v: opt
 do
-	case $opt in
-		d)
-			DEB_ISO=$OPTARG
-			;;
-		p)
-			PRESEED_FILE=$OPTARG
-			;;
-		v)
-			BUILD_VER=$OPTARG
-			;;
-		*)
-			exit 1
-			;;
-	esac
+    case $opt in
+        d)
+            DEB_ISO=$(readlink -f ${OPTARG})
+            ;;
+        p)
+            PRESEED_FILE=$(readlink -f ${OPTARG})
+            ;;
+        v)
+            BUILD_VER=$OPTARG
+            ;;
+        *)
+            exit 1
+            ;;
+    esac
 done
 
 if [ -z "${DEB_ISO}" ]; then
-	echo "Missing '-d DEBIAN.iso'"
-	exit 1
+    echo "Missing '-d DEBIAN.iso'"
+    exit 1
 fi
-
 if [ -z "${PRESEED_FILE}" ]; then
-	echo "Missing '-p PRESEED_FILE'"
-	exit 1
-else
-	PRESEED_FILE=$(readlink -f ${PRESEED_FILE})
+    echo "Missing '-p PRESEED_FILE'"
+    exit 1
+fi
+if [ -z "${BUILD_VER}" ]; then
+    echo "Missing '-v BUILD_VER'"
+    exit 1
+fi
+if [ ! -f "${DEB_ISO}" ]; then
+    echo "Debian ISO not found: ${DEB_ISO}"
+    exit 1
+fi
+if [ ! -f "${PRESEED_FILE}" ]; then
+    echo "Preseed file not found: ${PRESEED_FILE}"
+    exit 1
+fi
+if [ ! -d "$(pwd)/src" ]; then
+    echo "Script must be run from the project root directory"
+    exit 1
+fi
+if [ -f "$(pwd)/asl-debian-installer-${BUILD_VER}.iso" ]; then
+    echo "Move or delete $(pwd)/asl-debian-installer-${BUILD_VER}.iso"
+    exit 1
 fi
 
-if [ -z "${BUILD_VER}" ]; then
-	echo "Missing '-v BUILD_VER'"
-	exit 1
-fi
+## Patch the initrd
+patch_initrd() {
+    local f=$1
+    gunzip $f
+    local unpacked="${f%.gz}"
+    printf "preseed.cfg\nlate.sh" | cpio -H newc -o -A -F ${unpacked}
+    gzip ${unpacked}
+}
 
 set -x
 set -e
 
-TMP_DIR=$(mktemp -d)
+WORK_DIR=$(mktemp -d)
+#trap "rm -rf ${WORK_DIR}" EXIT
 
-if [ ! -d ${ISO_SRC} ]; then
-	mkdir ${ISO_SRC}
-else
-	chmod -R +w ${ISO_SRC}
-	rm -rf ${ISO_SRC}
-fi
+# Extract only the files we need to modify
+xorriso -osirrox on -indev ${DEB_ISO} \
+    -extract /boot/grub/grub.cfg    ${WORK_DIR}/grub.cfg \
+    -extract /boot/grub/efi.img     ${WORK_DIR}/efi.img \
+    -extract /isolinux/drk.cfg      ${WORK_DIR}/drk.cfg \
+    -extract /isolinux/drkgtk.cfg   ${WORK_DIR}/drkgtk.cfg \
+    -extract /isolinux/gtk.cfg      ${WORK_DIR}/gtk.cfg \
+    -extract /isolinux/menu.cfg     ${WORK_DIR}/menu.cfg \
+    -extract /isolinux/spkgtk.cfg   ${WORK_DIR}/spkgtk.cfg \
+    -extract /isolinux/txt.cfg      ${WORK_DIR}/txt.cfg \
+    -extract /install.amd/initrd.gz ${WORK_DIR}/initrd.gz \
+    -extract /install.amd/gtk/initrd.gz  ${WORK_DIR}/gtk-initrd.gz \
+    -extract /install.amd/xen/initrd.gz  ${WORK_DIR}/xen-initrd.gz \
+    --
+chmod +w ${WORK_DIR}/*
 
-
-# Unpack the ISO
-xorriso -osirrox on -indev $DEB_ISO \
-	 -extract / ${ISO_SRC}
-cd ${ISO_SRC}
-
-## Update Grub/EFI
-chmod -R +w boot/grub EFI/debian
-patch -p0 < ${SRC}/grub.patch
-cp boot/grub/grub.cfg boot/grub/x86_64-efi/grub.cfg
-cp boot/grub/grub.cfg EFI/debian/grub.cfg
-mcopy -Do -i boot/grub/efi.img boot/grub/grub.cfg ::efi/debian/grub.cfg
-mcopy -i boot/grub/efi.img ::efi/debian/grub.cfg /tmp/grub-efi-verify.cfg
-sha256sum boot/grub/grub.cfg boot/grub/x86_64-efi/grub.cfg \
-	EFI/debian/grub.cfg /tmp/grub-efi-verify.cfg
+## Update grub
+patch ${WORK_DIR}/grub.cfg < ${SRC}/grub.patch
+mcopy -Do -i ${WORK_DIR}/efi.img ${WORK_DIR}/grub.cfg ::EFI/debian/grub.cfg
+mcopy -i ${WORK_DIR}/efi.img ::EFI/debian/grub.cfg /tmp/grub-efi-verify.cfg
+sha256sum ${WORK_DIR}/grub.cfg /tmp/grub-efi-verify.cfg
 rm /tmp/grub-efi-verify.cfg
-chmod -R -w boot/grub EFI/debian
 
-## Update ISOLINUX
-chmod -R +w isolinux/
-patch -p0 < ${SRC}/isolinux.patch
-chmod -R -w isolinux/
+## Update isolinux
+patch -p1 -d ${WORK_DIR} < ${SRC}/isolinux.patch
 
-## Add preseed to the initrd
-chmod -R +w install.amd/
+## Patch the initrd
+cd ${WORK_DIR}
 cp ${PRESEED_FILE} preseed.cfg
 cp ${SRC}/late.sh late.sh
-find install.amd/ -name 'initrd.gz' -type f | while read f
-do
-	gunzip $f
-	f=$(echo $f | sed 's/\.gz//g')
-	echo preseed.cfg | cpio -H newc -o -A -F $f
-	echo late.sh | cpio -H newc -o -A -F $f
-	gzip $f
-done
-chmod -R -w install.amd/
+patch_initrd initrd.gz
+patch_initrd gtk-initrd.gz
+patch_initrd xen-initrd.gz
+cd -
 
-## Stage our custom files
-pwd
-cp ${SRC}/post-install.sh .
-chmod 755 post-install.sh
-mkdir asl3
-cp -r ${FIRSTBOOT_SRC} asl3/
-
-## Regnerate the md5sum.txt
-chmod +w md5sum.txt
-find -follow -type f ! -name md5sum.txt -print0 | xargs -0 md5sum > md5sum.txt
-chmod -w md5sum.txt
-
-## Build the preseeded image
-
-xorriso -as mkisofs \
-    -r \
-    -V "ASL Debian Installer" \
-    -o ../asl-debian-installer-$BUILD_VER.iso \
-    -J -joliet-long \
-    -cache-inodes \
-    -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
-    -b isolinux/isolinux.bin \
-      -no-emul-boot -boot-load-size 4 -boot-info-table \
-    -eltorito-alt-boot \
-    -e boot/grub/efi.img \
-      -no-emul-boot \
-    -isohybrid-gpt-basdat \
-    .
-
-## Cleanup
-chmod -R +w ${ISO_SRC}
-rm -rf ${ISO_SRC}
+## Build the preseeded image by overlaying changes onto the original ISO
+xorriso \
+    -indev ${DEB_ISO} \
+    -outdev $(pwd)/asl-debian-installer-${BUILD_VER}.iso \
+    -volid "ASL Debian Installer" \
+    -boot_image any replay \
+    -map ${WORK_DIR}/grub.cfg       /boot/grub/grub.cfg \
+    -map ${WORK_DIR}/grub.cfg       /boot/grub/x86_64-efi/grub.cfg \
+    -map ${WORK_DIR}/grub.cfg       /EFI/debian/grub.cfg \
+    -map ${WORK_DIR}/efi.img        /boot/grub/efi.img \
+    -map ${WORK_DIR}/drk.cfg        /isolinux/drk.cfg \
+    -map ${WORK_DIR}/drkgtk.cfg     /isolinux/drkgtk.cfg \
+    -map ${WORK_DIR}/gtk.cfg        /isolinux/gtk.cfg \
+    -map ${WORK_DIR}/menu.cfg       /isolinux/menu.cfg \
+    -map ${WORK_DIR}/spkgtk.cfg     /isolinux/spkgtk.cfg \
+    -map ${WORK_DIR}/txt.cfg        /isolinux/txt.cfg \
+    -map ${WORK_DIR}/initrd.gz      /install.amd/initrd.gz \
+    -map ${WORK_DIR}/gtk-initrd.gz      /install.amd/gtk/initrd.gz \
+    -map ${WORK_DIR}/xen-initrd.gz      /install.amd/xen/initrd.gz \
+    -map ${PRESEED_FILE}            /preseed.cfg \
+    -map ${SRC}/post-install.sh     /post-install.sh \
+    -map ${FIRSTBOOT_SRC}/          /asl3/ \
+    -commit
